export const USER_SELECTED = 'USER_SELECTED'
export const USER_FAILURE = 'USER_FAILURE'

export const USERS_REQUEST = 'USERS_REQUEST'
export const USERS_SUCCESS = 'USERS_SUCCESS'
export const USERS_FAILURE = 'USERS_FAILURE'